user/urls.py
from django.conf.urls import url
from django.urls import path
from .views import *

urlpatterns = [
    path("view/", listView, name="petient-list"),
    path("add/", create_petient, name="petient-create"),
    path("edit/<int:pk>/", edit_petient, name="petient-edit"),
    path("details/<int:pk>/", customer_details, name="petient-details"),
    path("delete/<int:pk>/", delete_petient, name="petient-delete"),

    path("ajax_form", ajax_form, name= "ajax-form"),
    path("list/", userList, name="list"),
]

user_dashboard/urls.py
from django.contrib import admin
from django.urls import path
from user.urls import urlpatterns as user_urls
from django.conf.urls import include, url
from django.conf import settings
from django.contrib.staticfiles.views import serve
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^dashboard/', include((user_urls, 'dashboard'), namespace='dashboard')),
]

if settings.DEBUG:
    urlpatterns += [
        # static files (images, css, javascript, etc.)
        url(r'^static/(?P<path>.*)$', serve)] + static(
            '/media/', document_root=settings.MEDIA_ROOT)

user/models.py
from django.db import models

# Create your models here.
from django.conf import settings
from django.contrib.auth.models import (
    AbstractBaseUser, BaseUserManager, PermissionsMixin)

class User(PermissionsMixin, AbstractBaseUser):
    first_name = models.CharField(max_length=256, blank=False, unique=True)
    last_name = models.CharField(max_length=256, blank=False)
    birth_date = models.DateField(null=True, blank=True)

    def __str__(self):
        return self.first_name + " " + self.last_name

    USERNAME_FIELD = 'first_name'

user/forms.py
from django import forms
from django.utils.translation import pgettext_lazy
from django.utils import timezone
from django.apps.registry import apps

User = apps.get_model('user', 'User')

class CustomerForm(forms.ModelForm):
    GENDER_TYPE = [
        ("male", "Male"),
        ("female", "Female"),
        ("other", "Other"),
    ]
    gender = forms.ChoiceField(required=False, choices=GENDER_TYPE)
    
    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)
        
        if self.instance:
            print(self.instance.birth_date)
            self.fields['birth_date'].initial = self.instance.birth_date
            


    def clean(self):
        cleaned_data = super().clean()
        if cleaned_data.get('birth_date'):
            if cleaned_data.get("birth_date") == timezone.now().date():
                raise forms.ValidationError({'birth_date': ["Birth Date can not be today's date",]})
            if cleaned_data.get("birth_date") > timezone.now().date():
                raise forms.ValidationError({'birth_date': ["Birth Date can not be greater than today's date",]})



    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'birth_date', 'gender']
        widgets = {
            'birth_date': forms.DateInput(format=('%Y-%m-%d'), attrs={'class':'form-control', 'placeholder':'Select a date', 'type':'date'}),
        }
        labels = {
            'first_name': pgettext_lazy(
                'Customer form: First name field', 'First Name'),
            'last_name': pgettext_lazy(
                'Customer form: Last name field', 'Last Name'),
            'birth_date': pgettext_lazy(
                'Customer form: birth date field', 'Date of Birth'),
            'gender': pgettext_lazy(
                'Customer form: gender field', 'Gender')
        }

user/views.py
from django.shortcuts import render
from django.apps.registry import apps
from django.template.response import TemplateResponse
from django.utils.translation import pgettext_lazy
from django.shortcuts import get_object_or_404, redirect
from django.contrib import messages
from django.http import JsonResponse
from django.core.paginator import Paginator
from django.views.generic.list import ListView

from .forms import CustomerForm

User = apps.get_model('user', 'User')

# class UserListView(ListView):
#     model = User
#     template_name = 'dashboard/petient/list.html'  
#     context_object_name = 'petients'  
#     paginate_by = 10
#     queryset = User.objects.all() 
def listView(request):
    return TemplateResponse(request, 'dashboard/petient/list_new.html')

def userList(request):
    data = []
    users = User.objects.all()
    for i in users:
        res = {}
        res['id'] = i.id
        res['first_name'] = i.first_name
        res['last_name'] = i.last_name
        res['birth_date'] = i.birth_date
        data.append(res)

    return JsonResponse(data, safe=False)



def create_petient(request):
    return TemplateResponse(request, 'dashboard/petient/form_new.html')

def ajax_form(request):
    if request.is_ajax():
        first_name = request.POST.get('first_name', None) 
        last_name = request.POST.get('last_name', None)
        birth_date = request.POST.get('birth_date', None)

        data = {
            "first_name": first_name,
            "last_name": last_name,
            "birth_date": birth_date
        }
        User.objects.create(**data)

        return JsonResponse({'msg':'Your form has been submitted successfully',
                            'status': True})

    


def edit_petient(request, pk=None):
    petient = get_object_or_404(User, pk=pk)
    form = CustomerForm(request.POST or None, instance=petient)
    if form.is_valid():
        form.save()

        msg = pgettext_lazy(
            'Dashboard message', 'Updated Petient %s') % petient
        messages.success(request, msg)
        return redirect('dashboard:petient-list')
    ctx = {'form': form, 'petient': petient}
    return TemplateResponse(request, 'dashboard/petient/form.html', ctx)

def customer_details(request, pk):
    queryset = User.objects.all()
    petient = get_object_or_404(queryset, pk=pk)
    ctx = {
        'petient': petient}
    return TemplateResponse(request, 'dashboard/petient/detail.html', ctx)

def delete_petient(request, pk=None):
    petient = get_object_or_404(User, pk=pk)
    petient.delete()
    msg = pgettext_lazy(
            'Dashboard message', 'Delete Petient %s') % petient
    messages.success(request, msg)
    return JsonResponse({"msg":"Petient Delete Successfully!", "success":True})

templates/dashboard/base.html
<!DOCTYPE html>

<html>
    <head>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">

            <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
            <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
            <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>

        <title>{% block title %} {% endblock title %} </title>
        {% block custom_css %}{% endblock %}
    </head>
    <body>
        <header>
            <div id="notification" class="col-md-offset-1 col-xs-offset-1 col col-md-6 col-xs-6 alert"><div></div></div>
        </header>
        <div class="subheader top-nav">
            <div class="nav-wrapper container">
                {% block breadcrumbs %}
                <ul class="breadcrumbs">
                    <li class="visible-s">
                        <a href="#">
                                Home
              
                        </a>
                    </li>
                </ul>
                {% endblock %}
                {% block header_extra %}{% endblock %}
            </div>
        </div>
       
        <main class="main">
            <div id="base-modal" class="modal"></div>
            <div id="base-modal-fixed" class="modal modal-fixed-footer"></div>
            <div class="container">
                {% block content %}{% endblock %}
                <div id="dashboard-app"></div>
            </div>
        </main>
    </body>
    {% block extra_script %}{% endblock extra_script %}
   
</html>

templates/dashboard/base_modal.html
{% load i18n %}

<form
  role="form" method="post" action="{% block action_url %}#!{% endblock %}"
  class="{% block form_class %}form-async{% endblock %}" novalidate>
  {% comment %}Empty form_class can be used for non-ajax forms with server redirect.{% endcomment %}
  {% csrf_token %}
  <div class="modal-content">
    <div class="row">
      <div class="col s12">
        <h5>
          {% block title %}{% endblock %}
        </h5>
      </div>
    </div>
    {% if form.non_field_errors %}
      <div class="col 12">
        {% for error in form.non_field_errors %}
          <p class="help-block materialize-red-text">{{ error }}</p>
        {% endfor %}
      </div>
    {% endif %}
    <div class="row">
      {% block content %}{% endblock %}
    </div>
  </div>
  <div class="modal-footer">
    <span class="left">
      {% block actions_left %}{% endblock %}
    </span>
    <a href="#!" class="modal-action modal-close btn-flat waves-effect">
      {% block cancel_action %} {% trans "Cancel" context "Dashboard cancel action" %} {% endblock %}
    </a>
    <button type="submit" class="modal-action btn-flat waves-effect">
      {% block primary_action %}{% endblock %}
    </button>
  </div>
</form>

templates/dashboard/base_zero_page.html
<div class="card zero-page">
  <div class="card-content">
    <div class="zero-page__title">
      {% block title %}{% endblock %}
    </div>
    <div class="zero-page__content">{% block content %}{% endblock %}</div>
  </div>
</div>

templates/dashboard/petient/detail.html
{% extends "dashboard/base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block title %}
  {% if petient.pk %}
    {{ petient }} | Details
  {% else %}
  Petient | Add
  {% endif %}
{% endblock %}

{% block breadcrumbs %}
  <ul class="breadcrumbs breadcrumbs--history">
    <li>
      <a href="{% url "dashboard:petient-list" %}">
        Petient
      </a> > {{ petient }}
    </li>
   
  </ul>
{% endblock %}

{% block content %}
<div class="row">
    <div class="col s12 l8">
        <div style="margin-top: 40px;">
            <div class="card">
                <div class="card-header">
                    <div class="row">
                        <div class="col-md-9">
                                Petient Details
                        </div>
                        <div class="col-md-3">
                                <a href="{% url "dashboard:petient-edit" pk=petient.pk %}"  class="btn btn-primary">Edit</a>
                        </div>
                    </div>
                    
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-3">
                                <h6 class="card-title">Name</h6>
                                <h6 class="card-title">Date of Birth</h6>
                        </div>
                        <div class="col-md-6">
                                
                                <p class="card-text">{{ petient }}</p>
                                <p class="card-text">{{ petient.birth_date }}</p>
                        </div>
                        
                    </div>
                   
                </div>
                </div>
            
        </div>
    </div>
</div>
{% endblock %}

templates/dashboard/petient/form.html
{% extends "dashboard/base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block title %}
  {% if petient.pk %}
    {{ petient }}
  {% else %}
  Petient | Add
  {% endif %}
{% endblock %}

{% block custom_css %}
<style>
  .errorlist
    {
        color: red;
    }
</style>

{% endblock %}
{% block breadcrumbs %}
  <ul class="breadcrumbs breadcrumbs--history">
    <li>
      <a href="{% url "dashboard:petient-list" %}">
        Petient
      </a> > {{ petient }}
    </li>
   
  </ul>
{% endblock %}
{% block content %}
<div class="row">
    <div class="col s12 l8">
        <div style="margin-top: 40px;"></div>
        
        {% if form %}
        <form class="" method="post" id="form-customer" enctype="multipart/form-data" novalidate>
           
                {% csrf_token %}
                <!-- {{ form }} -->
                {% for field in form.visible_fields %}
                <div class="form-group">
                {{ field.label_tag }}

                {% if form.is_bound %}
                    {% if field.errors %}
                    {% render_field field class="form-control is-invalid" %}
                    {% for error in field.errors %}
                        <div class="invalid-feedback">
                        {{ error }}
                        </div>
                    {% endfor %}
                    {% else %}
                    {% render_field field class="form-control is-valid" %}
                    {% endif %}
                {% else %}
                    {% render_field field class="form-control" %}
                {% endif %}

              
                </div>
            {% endfor %}
            
               
            <div class="card-action right-align">
            <a href="/dashboard/view/"  class="btn-flat waves-effect">
                    Cancel</a>
            {% if petient.pk %}
                <button type="submit" class="btn waves-effect customer-form-submit">
                    Update
                </button>
            {% else %}
                <button type="submit" class="btn waves-effect customer-form-submit">
                    Add
                </button>
            {% endif %}
            </div>
        </form>
        {% endif %}
    </div>
</div>
{% endblock %}

templates/dashboard/petient/form_new.html
{% extends "dashboard/base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block title %}
  {% if petient.pk %}
    {{ petient }}
  {% else %}
  Petient | Add
  {% endif %}
{% endblock %}

{% block custom_css %}
<style>
  .errorlist
    {
        color: red;
    }
</style>

{% endblock %}
{% block breadcrumbs %}
  <ul class="breadcrumbs breadcrumbs--history">
    <li>
      <a href="{% url "dashboard:petient-list" %}">
        Petient
      </a> > 
      {% if petient.pk %}
        Edit Petient > {{ petient }}
      {% else %}
        Add Petient
      {% endif %}
    </li>
   
  </ul>
{% endblock %}
{% block content %}
<form class="form" method="post" id="form-customer">
    {% csrf_token %}
    <div class="form-group">
      <label for="first_name">First Name:</label>
      <input type="text" class="form-control" id="first_name" name="first_name">
      <p id="firstname_error" style="color: red;" >**Firstname is missing
      </p>
    </div>
    <div class="form-group">
      <label for="last_name">Last Name:</label>
      <input type="text" class="form-control" id="last_name" name="last_name">
      <p id="lastname_error" style="color: red;" >**Lastname is missing
        </p>
    </div>

    <div class="form-group">
        <label for="birth_date">Date of Birth:</label>
        <input type="date" class="form-control" id="birth_date" name="birth_date">
    </div>

    <div class="form-group">
        <label for="gender">Gender:</label>
        <select class="form-control" id="gender">
            <option>Male</option>
            <option>Female</option>
            <option>Other</option>
          </select>
    </div>
    
    <button type="submit" class="btn btn-primary" id="submit">Submit</button>
  </form> 
{% endblock %}
{% block extra_script %}
<script>
$(document).ready(function () { 
  // validate first name
  $('#firstname_error').hide();    
  $('#first_name').keyup(function () {
      validateFirstname();
  });
    
  function validateFirstname() {
  var first_name = $('#first_name').val();
    if (first_name.length == '') {
    $('#firstname_error').show();
        return false;
    } 
    else {
        $('#firstname_error').hide();
    }
  }

  // validate first name
  $('#lastname_error').hide();    
  $('#last_name').keyup(function () {
      validateLastname();
  });
    
  function validateLastname() {
  var last_name = $('#last_name').val();
    if (last_name.length == '') {
    $('#lastname_error').show();
        return false;
    } 
    else {
        $('#lastname_error').hide();
    }
  }



$('#submit').on('click', function(e){
  e.preventDefault();
  validateFirstname()
  validateLastname()
  $.ajax({
       type : "POST", 
       url: "{% url 'dashboard:ajax-form' %}",
       data: {
        first_name : $('#first_name').val(),
        last_name : $('#last_name').val(),
        birth_date : $("#birth_date").val(),
        csrfmiddlewaretoken: '{{ csrf_token }}',
        dataType: "json",

       },
       
       success: function(data){
        if (data['status'] == true){
          window.location = "{% url 'dashboard:petient-list' %}";
        }
       },

       failure: function() {
           
       }


   });

});
});
</script>
{% endblock extra_script %}

templates/dashboard/petient/list.html
{% extends "dashboard/base.html" %}
{% load static %}


{% block title %}
  Petient | List
{% endblock title %}

{% block custom_css %}
<style>
    .btn-fab-fixed {
        right: calc(25% - 60px);
    }
    
    .btn-fab-fixed {
      position: absolute;
      top: 98px;
      right: 25%;
  }


    .btn-fab-default:hover{
        background-color: #26a5d4;
    }

    .btn-fab-default:hover{
       box-shadow: 0 3px 3px 0 rgba(0,0,0,.14),0 1px 7px 0 rgba(0,0,0,.12),0 3px 1px -1px rgba(0,0,0,.2);
    }

    .waves-effect {
        position: relative;
        cursor: pointer;
        display: inline-block;
        overflow: hidden;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
        -webkit-tap-highlight-color: transparent;
        vertical-align: middle;
        z-index: 1;
        transition: .3s ease-out;
    }

    .btn-fab-default {
        height: 54px;
        line-height: 54px;
        width: 56px;
    }
    
   
    .btn-fab-default {
        display: inline-block;
        color: #fff;
        position: relative;
        overflow: hidden;
        z-index: 1;
        width: 40px;
        height: 40px;
        line-height: 40px;
        padding: 0;
        background-color: #26a5d4;
        border-radius: 50%;
        transition: .3s;
        cursor: pointer;
        vertical-align: middle;
    }
 
    .btn-fab-default {
        text-decoration: none;
        color: #fff;
        background-color: #26a5d4;
        text-align: center;
        letter-spacing: .5px;
        transition: .2s ease-out;
        cursor: pointer;
    }

    .btn-fab-default svg {
        vertical-align: middle;
    }

    svg:not(:root) {
        overflow: hidden;
    }
    </style>
{% endblock %}

{% block breadcrumbs %}
  <ul class="breadcrumbs">
    <li class="visible-s">
        Petients
    </li>
  </ul>
{% endblock %}

{% block header_extra %}
  <div class="btn-fab-fixed">
    <a href="{% url 'dashboard:petient-create' %}" class="btn-fab-default waves-effect waves-light" >
    <svg fill="#ffffff" height="24" viewBox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" role="img" data-src="/static/admin/img/add.svg" class="injected-svg">
        <path d="M19 13h-6v6h-2v-6H5v-2h6V5h2v6h6v2z" role="presentation"></path>
        <path d="M0 0h24v24H0z" fill="none" role="presentation"></path>
    </svg>
    </a>
  </div>
{% endblock %}

{% block content %}

<div class="container">
  {% if petients %}
    <table class="table table-light table-striped" id="list_table">
      <thead>
        <tr>
          <th>Name</th>
          <th>Date of Birth</th>
          <th colspan="2">Action</th>
        </tr>
      </thead>
      <tbody>
      <!-- jinja2 Technique -->
      {% if petients %}  
      {% for petient in petients %}
        <tr>
          <td>{{petient}}</td>
          <td>{{petient.birth_date}}</td>
          <td>
            <button type="button" class="btn btn-light">
              <a href="{% url "dashboard:petient-details" pk=petient.pk %}" class="btn-flat waves-effect" >View</a></button>
              <button type="button" class="btn btn-light" id="delete" data-ref={{petient.pk}} style="cursor: pointer;">
                  Delete
              </button>
              

          </td>
        </tr>
      {% endfor %}
      {% endif %}
      </tbody>
    </table>

    {% if is_paginated %}
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
      {% else %}
        <li class="disabled"><span>&laquo;</span></li>
      {% endif %}
      {% for i in paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
        {% else %}
          <li><a href="?page={{ i }}">{{ i }}</a></li>
        {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
        <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
      {% else %}
        <li class="disabled"><span>&raquo;</span></li>
      {% endif %}
    </ul>
  {% endif %}
  {% else %}
  <h5>No Data found</h5>
  {% endif %}
  </div>
  </body>
  </html>
  <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js"></script>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.2/jquery-ui.min.js"></script>
  <script>
  $("#delete").on("click", function(event){
      event.preventDefault();
      var pk = $(this).attr('data-ref');
      var data = {
          "csrfmiddlewaretoken":$("input[name='csrfmiddlewaretoken']").val()
      };
      $.ajax({
          url: "/dashboard/delete/"+pk+"/",
          type: "GET",
          data: data,
          contentType: "application/json; charset=utf-8",
          dataType: "json",
          success: function (data) {
              if (data['success']){
                $("#list_table").load(window.location + " #list_table");
              }
          }
      });
  });
  </script>
  {% endblock %}

templates/dashboard/petient/list_new.html
{% extends "dashboard/base.html" %}
{% load static %}


{% block title %}
  Petient | List
{% endblock title %}

{% block custom_css %}
<style>
    .btn-fab-fixed {
        right: calc(25% - 60px);
    }
    
    .btn-fab-fixed {
      position: absolute;
      top: 98px;
      right: 25%;
  }


    .btn-fab-default:hover{
        background-color: #26a5d4;
    }

    .btn-fab-default:hover{
       box-shadow: 0 3px 3px 0 rgba(0,0,0,.14),0 1px 7px 0 rgba(0,0,0,.12),0 3px 1px -1px rgba(0,0,0,.2);
    }

    .waves-effect {
        position: relative;
        cursor: pointer;
        display: inline-block;
        overflow: hidden;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
        -webkit-tap-highlight-color: transparent;
        vertical-align: middle;
        z-index: 1;
        transition: .3s ease-out;
    }

    .btn-fab-default {
        height: 54px;
        line-height: 54px;
        width: 56px;
    }
    
   
    .btn-fab-default {
        display: inline-block;
        color: #fff;
        position: relative;
        overflow: hidden;
        z-index: 1;
        width: 40px;
        height: 40px;
        line-height: 40px;
        padding: 0;
        background-color: #26a5d4;
        border-radius: 50%;
        transition: .3s;
        cursor: pointer;
        vertical-align: middle;
    }
 
    .btn-fab-default {
        text-decoration: none;
        color: #fff;
        background-color: #26a5d4;
        text-align: center;
        letter-spacing: .5px;
        transition: .2s ease-out;
        cursor: pointer;
    }

    .btn-fab-default svg {
        vertical-align: middle;
    }

    svg:not(:root) {
        overflow: hidden;
    }
    </style>
{% endblock %}

{% block breadcrumbs %}
  <ul class="breadcrumbs">
    <li class="visible-s">
        Petients
    </li>
  </ul>
{% endblock %}

{% block header_extra %}
  <div class="btn-fab-fixed">
    <a href="{% url 'dashboard:petient-create' %}" class="btn-fab-default waves-effect waves-light" >
    <svg fill="#ffffff" height="24" viewBox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" role="img" data-src="/static/admin/img/add.svg" class="injected-svg">
        <path d="M19 13h-6v6h-2v-6H5v-2h6V5h2v6h6v2z" role="presentation"></path>
        <path d="M0 0h24v24H0z" fill="none" role="presentation"></path>
    </svg>
    </a>
  </div>
{% endblock %}

{% block content %}
<table class="table table-light table-striped" id="list_table">
    <thead>  
        <tr>
            <th>Name</th>
            <th>Date of Birth</th>
            <th colspan="2">Action</th>
        </tr>      
    </thead>
    <tbody>

    </tbody>
</table>
{% endblock %}

{% block extra_script %}
<script>
function myfunction(id) {
    var pk = id;
    var data = {
        "csrfmiddlewaretoken":$("input[name='csrfmiddlewaretoken']").val()
    };
    $.ajax({
        url: "/dashboard/delete/"+pk+"/",
        type: "GET",
        data: data,
        contentType: "application/json; charset=utf-8",
        dataType: "json",
        success: function (data) {
            if (data['success']){
            // $("#list_table").load(window.location + " #list_table");
            $('#tr_'+id).remove();
            
            }
        }
    });
}

$(document).ready(function () { 
    $.ajax({
       type : "GET", 
       url: "{% url 'dashboard:list' %}",
       data: {
       },
       
       success: function(data){
        $.each(data, function(key,val) {
            $('#list_table').append(
                    '<tr id="tr_'+val['id']+'"><td id="name">'+val['first_name']+" "+val['last_name']+'</td>' +
                    '<td id="birth_date">'+val['birth_date']+'</td><td><button type="button" class="btn btn-light"> \
                    <a href="/dashboard/details/'+val['id']+'/" class="btn-flat waves-effect" >View</a></button><button onclick="myfunction('+val['id']+')" style="margin-left:5px;" type="button" class="btn btn-light" id="delete_'+val['id']+'" data-ref='+val['id']+' style="cursor: pointer;">Delete</button></td></tr>')
                    ;

            });
        }


   });
   
});


// $("#delete").on("click", function(event){
//     //   event.preventDefault();
//       var pk = $(this).attr('data-ref');
//       var data = {
//           "csrfmiddlewaretoken":$("input[name='csrfmiddlewaretoken']").val()
//       };
//       $.ajax({
//           url: "/dashboard/delete/"+pk+"/",
//           type: "GET",
//           data: data,
//           contentType: "application/json; charset=utf-8",
//           dataType: "json",
//           success: function (data) {
//               if (data['success']){
//                 $("#list_table").load(window.location + " #list_table");
//               }
//           }
//       });
//   });
</script>
{% endblock %}

templates/dashboard/petient/modal/confirm_delete.html
{% extends "dashboard/base_modal.html" %}

{% block action_url %}
{% url 'dashboard:petient-delete' pk=petient.pk %}
{% endblock %}

{% block title %}
  Remove petient {{ petient }}
{% endblock %}

{% block content %}
  <div class="col s12">
      Are you sure you want to remove customer <strong>{{ petient }}</strong>?
     
  </div>
{% endblock content %}

{% block primary_action %}
Remove
{% endblock %}

templates/dashboard/petient/zero_page.html
{% extends 'dashboard/base_zero_page.html' %}
{% load i18n %}
{% load static %}

{% block title %}{% trans "No customers found." %}{% endblock %}
{% block content %}
  
    Petients list will appear here once you add.
{% endblock %}